# BentoXGBoost Configuration File

# Default project to use if none is specified
default_project: "cancer_classification"

# Project configurations
projects:
  # Cancer classification project using the default dataset
  cancer_classification:
    description: "Breast cancer classification using the default dataset"
    model_name: "cancer"
    data_source: "default"
    parameters:
      max_depth: 3
      eta: 0.3
      max_features: 1000
      positive_ratio: 0.5
  
  # GitHub project example
  github_project:
    description: "Model trained on GitHub repository data"
    model_name: "github_model"
    data_source: "github"
    source_url: "https://github.com/KolbySisk/next-supabase-stripe-starter/archive/refs/heads/main.zip"
    parameters:
      max_depth: 4
      eta: 0.2
      max_features: 1500
      positive_ratio: 0.6
  
  # Web content project example
  web_project:
    description: "Model trained on web content"
    model_name: "web_model"
    data_source: "web"
    source_url: "https://www.cancer.org/cancer/types/breast-cancer/about/what-is-breast-cancer.html"
    parameters:
      max_depth: 3
      eta: 0.3
      max_features: 1200
      positive_ratio: 0.5
  
  # Crawled website project example
  crawl_project:
    description: "Model trained on crawled website content"
    model_name: "crawl_model"
    data_source: "crawl"
    source_url: "https://www.cancer.org/cancer/types/breast-cancer/"
    parameters:
      max_depth: 5
      eta: 0.25
      max_features: 2000
      positive_ratio: 0.5
      max_pages: 5
